 const operators = [
      {
        name: 'Achim Paribahan (আছিম পরিবহন)',
        stations: [
  "Gabtoli",
  "Technical",
  "Ansar Camp",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Jamuna Future Park",
  "Bashundhara",
  "Nadda",
  "Notun Bazar",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda",
  "Badda",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter"
],
 },
     {
        name: 'Active Paribahan (এক্টিভ পরিবহন)',
        stations: [
  "Shia Masjid",
  "Adabor",
  "Shyamoli",
  "Technical",
  "Ansar Camp",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewrapara",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur"
],
 },
      {
        name: 'Agradut (অগ্রদূত)',
        stations:[
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Golshan 1",
  "Badda Link Road",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda",
  "Notun Bazar"
],
   },
      {
        name: 'Airport Bangabandhu Avenue Paribahan (এয়ারপোর্ট বঙ্গবন্ধু এভিনিউ পরিবহন)',
        stations:[
  "Fulbaria",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bangla Motor",
  "Kawran Bazar",
  "Farmgate",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Kurmitola",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "House Building",
  "Abdullahpur"
],
      },
      {
        name: 'Azmeri Glory Limited (আজমেরী গ্লোরী লিমিটেড)',
        stations:[
  "Sadarghat",
  "Ray Saheb Bazar",
  "Naya Bazar",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibagh",
  "Mouchak",
  "Nabisco",
  "Mohakhali",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Konabari",
  "Chandra"
],
      },
      {
        name: 'Ajmi (আজমী)',
        stations:[
  "Dhamrai",
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Kalabagan",
  "City College",
  "New Market",
  "Nilkhet",
  "Azimpur",
  "Bakshi Bazar",
  "Gulistan",
  "Chittagong Road"
],
      },
      {
        name: 'Akash (আকাশ)',
        stations:[
  "Kadamtali",
  "Keraniganj",
  "Babubazar",
  "Naya Bazar",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibagh",
  "Mouchak",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Merul Badda",
  "Badda",
  "Shahjadpur",
  "Bashtola",
  "Notun Bazar",
  "Nadda",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi"
],
   },
      {
        name: 'Akik (আকিক))',
        stations: [
  "Ansar Camp",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Jamuna Future Park",
  "Bashundhara",
  "Nadda",
  "Notun Bazar",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda"
],
      },
      {
        name: 'Al Makka (আল মক্কা)',
        stations:  [
  "Motijheel",
  "Gulistan",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibagh",
  "Mouchak",
  "Mogbazar",
  "Nabisco",
  "Mohakhali",
  "Chairman Bari",
  "Kakali",
  "Banani",
  "ECB Square",
  "Kalshi",
  "Purobi",
  "Mirpur 10",
  "Mirpur 2",
  "Mirpur 1"
],
      },
         {
        name: 'Al Madina Plus One (আল মনিদা প্লাস ওয়ান)',
        stations:[
  "Nandan Park",
  "Zirani Bazar",
  "Baipayl",
  "Nobinagar",
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel",
  "Kamalapur"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations:[
  "Mirpur 14",
  "Mirpur 10",
  "Mirpur 2",
  "Sony Cinema Hall",
  "Mirpur 1",
  "Mazar Road",
  "Konabari",
  "Rupnagar",
  "Beribadh",
  "Birulia",
  "Ashulia",
  "Zirabo",
  "Fantasy Kingdom",
  "Nandan Park"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations:[
  "Shia Masjid",
  "Japan Garden City",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Golshan 1",
  "Badda Link Road",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations: [
  "Mirpur 1",
  "Mirpur 2",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Agargaon",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Golshan 1",
  "Badda Link Road",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations:[
  "Japan Garden City",
  "Ring Road",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Abdullahpur",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Kakali",
  "Banani",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building"
],
      },
         {
        name: 'Anabil Super (অনাবিল সুপার)',
        stations:[
  "Sign Board",
  "Shonir Akhra",
  "Jatrabari",
  "Mugdapara",
  "Bashabo",
  "Khilgaon",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Rampura Bridge",
  "Merul Badda",
  "Uttar Badda",
  "Shahjadpur",
  "Nadda",
  "Bashtola",
  "Notun Bazar",
  "Khilkhet",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Jashimuddin (Uttara)",
  "Airport",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Gazipur Chourasta"
],
      },
        {
        name: 'Arnob (অরনব)',
        stations:[
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Abdullahpur",
  "Badda Link Road",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter",
  "Sign Board"
  
],
      },
       {
        name: 'Ashirbad Pahibahan (আশীর্বাদ পরিবহন)',
        stations:[
  "Duairipara",
  "Rupnagar Abashik",
  "Shiyal Bari",
  "Proshika Moor",
  "Mirpur 2",
  "Mirpur 1",
  "Ansar Camp",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Shukrabad",
  "Dhanmondi 32",
  "Kalabagan",
  "City College",
  "New Market",
  "Nilkhet",
  "Azimpur"
  
],
      },
             {
        name: 'Ashulia Classic (আশুলিয়া ক্লাসিক)',
        stations:[
  "Nobinagar",
  "Baipayl",
  "Jamgora",
  "Fantasy Kingdom",
  "Zirabo",
  "Asulia Bazar",
  "Kamarpara",
  "Abdullahpur",
  "House Building",
  "Azampur",
  "Rajlakshmi",
  "Jashimuddin (Uttara)",
  "Airport",
  "Khilkhet",
  "Kuril Bishwa Road",
  "Shewra",
  "MES",
  "Kakali",
  "Banani",
  "Chairman Bari",
  "Mohakhali",
  "Nabisco",
  "Sat rasta"
],

      },
             {
        name: 'Asmani (আসমানী)',
        stations:[
  "Dhour",
  "Abdullahpur",
  "House Building",
  "Azampur",
  "Rajlakshmi",
  "Jashimuddin (Uttara)",
  "Airport",
  "Khilkhet",
  "Kuril Bishwa Road",
  "Jamuna Future Park",
  "Bashundhara",
  "Nadda",
  "Notun Bazar",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda",
  "Badda",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter",
  "Tarabo",
  "Madanpur"
  
],
      },
             {
        name: 'ATCL (এটিসিএল)',
        stations:[
  "Mohammadpur",
  "Asad Gate",
  "Shukrabad",
  "Kalabagan",
  "City College",
  "Science Lab",
  "Katabon",
  "Bata Signal",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Arambagh Notre Dame College"
  
],
      },
             {
        name: 'Ayat (আয়াত)',
        stations:[
  "Chiriyakhana",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Mogbazar",
  "Mouchak",
  "Malibaag Moor",
  "Rajarbag",
  "Kamalapur"
  
],
      },
             {
        name: 'Bahon (বাহন)',
        stations:[
  "Mirpur 14",
  "Mirpur 10",
  "Mirpur 2",
  "Mirpur 1",
  "Ansar Camp",
  "Bangla College",
  "Technical",
  "Darussalam",
  "Kallyanpur",
  "Shyamoli",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Kalabagan",
  "Science Lab",
  "Katabon",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "Dainik Bangla Moor",
  "Motijheel",
  "Arambagh",
  "Kamalapur",
  "Mugdapara",
  "Bashabo",
  "Khilgaon"
  
],
      },
             {
        name: 'Baishakhi (বৈশাখী)',
        stations:[
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Gulshan 1",
  "Badda Link Road",
  "Bashtola",
  "Uttar Badda",
  "Notun Bazar"
  
],
      },
             {
        name: 'Balaka (বলাকা)',
        stations:[
  "Sayapabad",
  "Manik Nagar",
  "TT Para",
  "Kamalapur",
  "Malibaag Moor",
  "Mouchak",
  "Mogbazar",
  "Sat rasta",
  "Nabisco",
  "Mohakhali",
  "Chairman Bari",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Gazipur Chourasta"
  
],
      },
             {
        name: 'Basumati Transport (বাসুমতি ট্রান্সপোর্ট)',
        stations:[
  "Basumati",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Manik Mia Avenue",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Golap Shah Mazar",
  "Naya Bazar",
  "Babubazar",
  "Keraniganj",
  "Maowa"
  
],
      },
             {
        name: 'Basumati Transport (বাসুমতি ট্রান্সপোর্ট)',
        stations:[
  "Basumati",
  "Gabtoli",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Chourasta"
],

      },
                {
        name: 'Best Satabdi (বেষ্ট শতাব্দী)',
        stations:[
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Khamar Bari",
  "Farmgate",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Dia Bari"
],
  
      },
                {
        name: 'Best Transport (বেষ্ট ট্রান্সপোর্ট)',
        stations:[
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel",
  "Sayapabad",
  "Jatrabari"
],
  

      },
           {
        name: 'Bhuiyan Paribahan (ভূঁইয়া পরিবহন)',
        stations:[
  "Japan Garden City",
  "Ring Road",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Old Airport",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Kakali",
  "Banani",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur"
],
  

      },
                {
        name: 'Bihanga (বিহঙ্গ)',
        stations:[
  "Mirpur 12",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Agargaon",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Gulshan Bridge",
  "Gulshan 1",
  "Badda",
  "Notun Bazar"
],
  

      },
                {
        name: 'Bikalpa (বিকল্প)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 1",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Bijoy Sarani",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel"
],
  

      },
    
           {
        name: 'Bikalpa (বিকল্প সুপার সার্ভিস)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Kalabagan",
  "City College",
  "New Market",
  "Nilkhet",
  "Azimpur",
  "Dhakeshwari"
],
      },
                {
        name: 'Bikash (বিকাশ)',
        stations:[
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Khamar Bari",
  "Farmgate",
  "Jahangir Gate",
  "Mohakhali",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Abdullahpur",
  "Kamarpara"
],
      },
                {
        name: 'Bikash Paribahan (বিকাশ পরিবহন)',
        stations:[
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Sayapabad",
  "Gulistan",
  "Chankhar Pul",
  "Bakshi Bazar",
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Khamar Bari",
  "Farmgate",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Kamarpara",
  "Dhour"
],
      },
                {
        name: 'Bondhu Paribahan (বন্ধু পরিবহন)',
        stations:[
    "Gulistan",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar"
  ],
      },
             {
        name: 'Borak (বোরাক)',
        stations:[
    "Palashi",
    "Chittagong Road",
    "Sonargao",
    "Chasara",
    "Meghna Ghat"
  ],
      },
                {
        name: 'Bashumoti (বসুমতি)',
        stations:[
    "Gazipur Chourasta",
    "Tongi",
    "Airport",
    "Khilkhet",
    "Kalshi",
    "Pallabi",
    "Mirpur 11",
    "Mirpur 10",
    "Mirpur 1",
    "Gabtoli"
  ],
      },
             {
        name: 'Brihottor (বৃহত্তর মিরপুর)',
        stations:[
    "Chiriyakhana",
    "Mirpur 1",
    "Gabtoli",
    "Amin Bazar",
    "Savar",
    "Nobinagar",
    "Chandra"
  ],
      },
     
    
    

    ];

 // Search logic
    function searchRoutes() {
      const from = document.getElementById('from').value.trim();
      const to = document.getElementById('to').value.trim();
      const resultDiv = document.getElementById('results');
      resultDiv.innerHTML = '';

      if (!from || !to) {
        resultDiv.innerHTML = '<p style="color:red;">Please enter both From and To stations.</p>';
        return;
      }

      const matchingOperators = operators.filter(op =>
        op.stations.includes(from) && op.stations.includes(to)
      );

      if (matchingOperators.length > 0) {
        resultDiv.innerHTML = '<h3>Operators serving this route:</h3>';

        const container = document.createElement('div'); // container div

        matchingOperators.forEach(op => {
          const item = document.createElement('div'); // individual operator box
          item.textContent = op.name;
          item.className = 'result-item'; // apply style
          container.appendChild(item);
        });

        resultDiv.appendChild(container);
      } else {
        resultDiv.innerHTML = `<p>No operators found for route from <strong>${from}</strong> to <strong>${to}</strong>.</p>`;
      }
    }







