 const operators = [
      {
        name: 'Achim Paribahan (আছিম পরিবহন)',
        stations: [
  "Gabtoli",
  "Technical",
  "Ansar Camp",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Jamuna Future Park",
  "Bashundhara",
  "Nadda",
  "Notun Bazar",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda",
  "Badda",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter"
],
 },
     {
        name: 'Active Paribahan (এক্টিভ পরিবহন)',
        stations: [
  "Shia Masjid",
  "Adabor",
  "Shyamoli",
  "Technical",
  "Ansar Camp",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewrapara",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur"
],
 },
      {
        name: 'Agradut (অগ্রদূত)',
        stations:[
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Golshan 1",
  "Badda Link Road",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda",
  "Notun Bazar"
],
   },
      {
        name: 'Airport Bangabandhu Avenue Paribahan (এয়ারপোর্ট বঙ্গবন্ধু এভিনিউ পরিবহন)',
        stations:[
  "Fulbaria",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bangla Motor",
  "Kawran Bazar",
  "Farmgate",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Kurmitola",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "House Building",
  "Abdullahpur"
],
      },
      {
        name: 'Azmeri Glory Limited (আজমেরী গ্লোরী লিমিটেড)',
        stations:[
  "Sadarghat",
  "Ray Saheb Bazar",
  "Naya Bazar",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibagh",
  "Mouchak",
  "Nabisco",
  "Mohakhali",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Konabari",
  "Chandra"
],
      },
      {
        name: 'Ajmi (আজমী)',
        stations:[
  "Dhamrai",
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Kalabagan",
  "City College",
  "New Market",
  "Nilkhet",
  "Azimpur",
  "Bakshi Bazar",
  "Gulistan",
  "Chittagong Road"
],
      },
      {
        name: 'Akash (আকাশ)',
        stations:[
  "Kadamtali",
  "Keraniganj",
  "Babubazar",
  "Naya Bazar",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibagh",
  "Mouchak",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Merul Badda",
  "Badda",
  "Shahjadpur",
  "Bashtola",
  "Notun Bazar",
  "Nadda",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi"
],
   },
      {
        name: 'Akik (আকিক))',
        stations: [
  "Ansar Camp",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Jamuna Future Park",
  "Bashundhara",
  "Nadda",
  "Notun Bazar",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda"
],
      },
      {
        name: 'Al Makka (আল মক্কা)',
        stations:  [
  "Motijheel",
  "Gulistan",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibagh",
  "Mouchak",
  "Mogbazar",
  "Nabisco",
  "Mohakhali",
  "Chairman Bari",
  "Kakali",
  "Banani",
  "ECB Square",
  "Kalshi",
  "Purobi",
  "Mirpur 10",
  "Mirpur 2",
  "Mirpur 1"
],
      },
         {
        name: 'Al Madina Plus One (আল মনিদা প্লাস ওয়ান)',
        stations:[
  "Nandan Park",
  "Zirani Bazar",
  "Baipayl",
  "Nobinagar",
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel",
  "Kamalapur"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations:[
  "Mirpur 14",
  "Mirpur 10",
  "Mirpur 2",
  "Sony Cinema Hall",
  "Mirpur 1",
  "Mazar Road",
  "Konabari",
  "Rupnagar",
  "Beribadh",
  "Birulia",
  "Ashulia",
  "Zirabo",
  "Fantasy Kingdom",
  "Nandan Park"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations:[
  "Shia Masjid",
  "Japan Garden City",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Golshan 1",
  "Badda Link Road",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations: [
  "Mirpur 1",
  "Mirpur 2",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Agargaon",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Golshan 1",
  "Badda Link Road",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree"
],
      },
         {
        name: 'Alif (আলিফ)',
        stations:[
  "Japan Garden City",
  "Ring Road",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Abdullahpur",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Kakali",
  "Banani",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building"
],
      },
         {
        name: 'Anabil Super (অনাবিল সুপার)',
        stations:[
  "Sign Board",
  "Shonir Akhra",
  "Jatrabari",
  "Mugdapara",
  "Bashabo",
  "Khilgaon",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Rampura Bridge",
  "Merul Badda",
  "Uttar Badda",
  "Shahjadpur",
  "Nadda",
  "Bashtola",
  "Notun Bazar",
  "Khilkhet",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Jashimuddin (Uttara)",
  "Airport",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Gazipur Chourasta"
],
      },
        {
        name: 'Arnob (অরনব)',
        stations:[
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Abdullahpur",
  "Badda Link Road",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter",
  "Sign Board"
  
],
      },
       {
        name: 'Ashirbad Pahibahan (আশীর্বাদ পরিবহন)',
        stations:[
  "Duairipara",
  "Rupnagar Abashik",
  "Shiyal Bari",
  "Proshika Moor",
  "Mirpur 2",
  "Mirpur 1",
  "Ansar Camp",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Shukrabad",
  "Dhanmondi 32",
  "Kalabagan",
  "City College",
  "New Market",
  "Nilkhet",
  "Azimpur"
  
],
      },
             {
        name: 'Ashulia Classic (আশুলিয়া ক্লাসিক)',
        stations:[
  "Nobinagar",
  "Baipayl",
  "Jamgora",
  "Fantasy Kingdom",
  "Zirabo",
  "Asulia Bazar",
  "Kamarpara",
  "Abdullahpur",
  "House Building",
  "Azampur",
  "Rajlakshmi",
  "Jashimuddin (Uttara)",
  "Airport",
  "Khilkhet",
  "Kuril Bishwa Road",
  "Shewra",
  "MES",
  "Kakali",
  "Banani",
  "Chairman Bari",
  "Mohakhali",
  "Nabisco",
  "Sat rasta"
],

      },
             {
        name: 'Asmani (আসমানী)',
        stations:[
  "Dhour",
  "Abdullahpur",
  "House Building",
  "Azampur",
  "Rajlakshmi",
  "Jashimuddin (Uttara)",
  "Airport",
  "Khilkhet",
  "Kuril Bishwa Road",
  "Jamuna Future Park",
  "Bashundhara",
  "Nadda",
  "Notun Bazar",
  "Bashtola",
  "Shahjadpur",
  "Uttar Badda",
  "Badda",
  "Madhya Badda",
  "Merul Badda",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter",
  "Tarabo",
  "Madanpur"
  
],
      },
             {
        name: 'ATCL (এটিসিএল)',
        stations:[
  "Mohammadpur",
  "Asad Gate",
  "Shukrabad",
  "Kalabagan",
  "City College",
  "Science Lab",
  "Katabon",
  "Bata Signal",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Arambagh Notre Dame College"
  
],
      },
             {
        name: 'Ayat (আয়াত)',
        stations:[
  "Chiriyakhana",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Mogbazar",
  "Mouchak",
  "Malibaag Moor",
  "Rajarbag",
  "Kamalapur"
  
],
      },
             {
        name: 'Bahon (বাহন)',
        stations:[
  "Mirpur 14",
  "Mirpur 10",
  "Mirpur 2",
  "Mirpur 1",
  "Ansar Camp",
  "Bangla College",
  "Technical",
  "Darussalam",
  "Kallyanpur",
  "Shyamoli",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Kalabagan",
  "Science Lab",
  "Katabon",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "Dainik Bangla Moor",
  "Motijheel",
  "Arambagh",
  "Kamalapur",
  "Mugdapara",
  "Bashabo",
  "Khilgaon"
  
],
      },
             {
        name: 'Baishakhi (বৈশাখী)',
        stations:[
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Gulshan 1",
  "Badda Link Road",
  "Bashtola",
  "Uttar Badda",
  "Notun Bazar"
  
],
      },
             {
        name: 'Balaka (বলাকা)',
        stations:[
  "sayadabad",
  "Manik Nagar",
  "TT Para",
  "Kamalapur",
  "Malibaag Moor",
  "Mouchak",
  "Mogbazar",
  "Sat rasta",
  "Nabisco",
  "Mohakhali",
  "Chairman Bari",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Gazipur Chourasta"
  
],
      },
             {
        name: 'Basumati Transport (বাসুমতি ট্রান্সপোর্ট)',
        stations:[
  "Basumati",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Manik Mia Avenue",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Golap Shah Mazar",
  "Naya Bazar",
  "Babubazar",
  "Keraniganj",
  "Maowa"
  
],
      },
             {
        name: 'Basumati Transport (বাসুমতি ট্রান্সপোর্ট)',
        stations:[
  "Basumati",
  "Gabtoli",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Chourasta"
],

      },
                {
        name: 'Best Satabdi (বেষ্ট শতাব্দী)',
        stations:[
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Khamar Bari",
  "Farmgate",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Dia Bari"
],
  
      },
                {
        name: 'Best Transport (বেষ্ট ট্রান্সপোর্ট)',
        stations:[
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel",
  "sayadabad",
  "Jatrabari"
],
  

      },
           {
        name: 'Bhuiyan Paribahan (ভূঁইয়া পরিবহন)',
        stations:[
  "Japan Garden City",
  "Ring Road",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Zia Uddyan",
  "Bijoy Sarani",
  "Old Airport",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Kakali",
  "Banani",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur"
],
  

      },
                {
        name: 'Bihanga (বিহঙ্গ)',
        stations:[
  "Mirpur 12",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Agargaon",
  "Bijoy Sarani",
  "Jahangir Gate",
  "Mohakhali",
  "Wireless",
  "Gulshan Bridge",
  "Gulshan 1",
  "Badda",
  "Notun Bazar"
],
  

      },
                {
        name: 'Bikalpa (বিকল্প)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 1",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Bijoy Sarani",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel"
],
  

      },
    
           {
        name: 'Bikalpa (বিকল্প সুপার সার্ভিস)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Kalabagan",
  "City College",
  "New Market",
  "Nilkhet",
  "Azimpur",
  "Dhakeshwari"
],
      },
                {
        name: 'Bikash (বিকাশ)',
        stations:[
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Khamar Bari",
  "Farmgate",
  "Jahangir Gate",
  "Mohakhali",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Abdullahpur",
  "Kamarpara"
],
      },
                {
        name: 'Bikash Paribahan (বিকাশ পরিবহন)',
        stations:[
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "sayadabad",
  "Gulistan",
  "Chankhar Pul",
  "Bakshi Bazar",
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Khamar Bari",
  "Farmgate",
  "Jahangir Gate",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Kamarpara",
  "Dhour"
],
      },
                {
        name: 'Bondhu Paribahan (বন্ধু পরিবহন)',
        stations:[
    "Gulistan",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar"
  ],
      },
             {
        name: 'Borak (বোরাক)',
        stations:[
    "Palashi",
    "Chittagong Road",
    "Sonargao",
    "Chasara",
    "Meghna Ghat"
  ],
      },
                {
        name: 'Bashumoti (বসুমতি)',
        stations:[
    "Gazipur Chourasta",
    "Tongi",
    "Airport",
    "Khilkhet",
    "Kalshi",
    "Pallabi",
    "Mirpur 11",
    "Mirpur 10",
    "Mirpur 1",
    "Gabtoli"
  ],
      },
             {
        name: 'Brihottor (বৃহত্তর মিরপুর)',
        stations:[
    "Chiriyakhana",
    "Mirpur 1",
    "Gabtoli",
    "Amin Bazar",
    "Savar",
    "Nobinagar",
    "Chandra"
  ],
      },
        {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Madanpur",
    "Kanchpur",
    "Chittagong Road",
    "Sign Board",
    "Matuail",
    "Rayerbag",
    "Shonir Akhra",
    "Jatrabari",
    "Sayadabad",
    "Gulistan",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Khamar Bari",
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar"
  ],
      },
        {
        name: 'BRTC Elevated Expressway (বিআরটিসি ভায়া এলিভেটেড এক্সপ্রেসওয়ে)',
        stations:[
    "Rajlakshmi",
    "Airport",
    "Kawlar",
    "Elevated Express Way",
    "Tejgaon College (Farmgate)",
    "Khejur Bagan",
    "Songsod Bhaban",
    "Bijoy Sarani",
    "Elevated Express Way",
    "Kawlar",
    "Airport",
    "Rajlakshmi"
  ],
      },
     
        {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Motijheel",
    "Gulistan",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Jahangir Gate",
    "Mohakhali",
    "Chairman Bari",
    "Kakali",
    "Banani",
    "Staff Road",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur",
    "Tongi"
  ],
      },
     
        {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Mohammadpur",
    "Asad Gate",
    "Khamar Bari",
    "Farmgate",
    "Jahangir Gate",
    "Mohakhali",
    "Wireless",
    "Gulshan 1",
    "Badda Link Road",
    "Uttar Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road"
  ],
      },
      {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Kamalapur",
    "Motijheel",
    "Gulistan",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Jahangir Gate",
    "Mohakhali",
    "Wireless",
    "Gulshan 1",
    "Badda Link Road",
    "Uttar Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road"
  ],
      },
        {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Vulta",
    "Kanchan Bridge",
    "Nila Market",
    "300 Feet",
    "Bashundhara (300 Feet Gate)",
    "Kuril Bishwa Road"
  ],
      },
     
        {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Motijheel",
    "Gulistan",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur"
  ],
      },
     
        {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Mohammadpur",
    "Star Kabab",
    "Dhanmondi",
    "Jigatola",
    "City College",
    "Science Lab",
    "Shahbag",
    "Matsya Bhaban",
    "High Court",
    "Press Club",
    "Paltan",
    "GPO",
    "Gulistan",
    "Motijheel"
  ],
      },
     {
        name: 'BRTC (বি আর টিসি)',
        stations:[
    "Gabtoli",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur",
    "Tongi",
    "Mill Gate",
    "Board Bazar",
    "Gazipur Bypass",
    "Gazipur Chourasta"
  ],
      },
        {
        name: 'BRTC Articulated (বি আর টিসি আরটিকুলেটেড)',
        stations:[
    "Balughat",
    "Cantonment",
    "Bijoy Sarani",
    "Farmgate",
    "Bangla Motor",
    "Shahbag",
    "Paltan",
    "Gulistan",
    "Motijheel"
  ],
      },
     
        {
        name: 'Cantonment (ক্যান্টনমেন্ট)',
        stations:[
    "Cantonment",
    "Mirpur 14",
    "Mirpur 10",
    "Mirpur 2",
    "Sony Cinema Hall",
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar"
  ],
      },
     
        {
        name: 'Cantonment Mini Service (ক্যান্টনমেন্ট মিনি সার্ভিস)',
        stations:[
    "Mirpur 14",
    "Sainik Club",
    "Kakali",
    "Banani",
    "Mohakhali"
  ],
      },
        {
        name: 'Champion (চ্যাম্পিয়ন)',
        stations:[
    "Vashantek",
    "Mirpur 14",
    "Mirpur 10",
    "Mirpur 2",
    "Sony Cinema Hall",
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Gabtoli"
  ],
      },
     
        {
        name: 'City Link (সিটি লিংক)',
        stations:[
    "Chittagong Road",
    "Sign Board",
    "Matuail",
    "Rayerbag",
    "Shonir Akhra",
    "Jatrabari",
    "Sayadabad",
    "Gulistan",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bata Signal",
    "Science Lab",
    "City College",
    "Jigatola",
    "Dhanmondi 15",
    "Star Kabab",
    "Mohammadpur",
    "Bosila",
    "Ghatar Char"
  ],
      },
     {
        name: 'D Link (ডি লিংক)',
        stations:[
    "Fulbaria",
    "Chankhar Pul",
    "Bakshi Bazar",
    "Azimpur",
    "Nilkhet",
    "New Market",
    "City College",
    "Kalabagan",
    "Dhanmondi 32",
    "Dhanmondi 27",
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Darussalam",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar",
    "Dhamrai"
  ],
      },
        {
        name: 'D One Transport (ডি ওয়ান)',
        stations:[
    "Motijheel",
    "Dainik Bangla Moor",
    "Paltan",
    "Press Club",
    "Matsya Bhaban",
    "High Court",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Nobinagar",
    "Dhamrai"
  ],
      },
     
        {
        name: 'Desh Bangla (দেশ বাংলা)',
        stations:[
    "Postogola",
    "Dholairpar",
    "Jatrabari",
    "Sayadabad",
    "Mugdapara",
    "Malibagh",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Uttar Badda",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Chourasta",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Abdullahpur",
    "Kamarpara"
  ],
      },
    {
        name: 'Dewan (দেওয়ান)',
        stations:[
    "Azimpur",
    "Eden College",
    "Nilkhet",
    "New Market",
    "Science Lab",
    "City College",
    "Science Lab",
    "Katabon",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Jahangir Gate",
    "Mohakhali",
    "Wireless",
    "Gulshan 1",
    "Badda",
    "Badda Link Road",
    "Uttar Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road"
  ],
      },
     
        {
        name: 'Dhakar Chaka (ঢাকার চাকা)',
        stations:[
  "Police Plaza",
  "Gulshan 1",
  "Gulshan 2"
],
      },
    {
        name: 'Dhakar Chaka (ঢাকার চাকা)',
        stations:[
  "Banani",
  "Gulshan 2",
  "Notun Bazar"
],
      },
     
        {
        name: 'Dhaka Metro Service (ঢাকার মেট্রো সার্ভিস)',
        stations:[
  "Mirpur 1",
  "Kallyanpur",
  "Shyamoli",
  "Asad Gate",
  "Shukrabad",
  "Kalabagan",
  "Science Lab",
  "New Market",
  "Nilkhet",
  "Azimpur"
],
      },
      {
        name: 'Dhaka Paribahan (ঢাকা পরিবহন)',
        stations:[
  "Gulistan",
  "Shahbag",
  "Farmgate",
  "Banani",
  "Uttara",
  "Shib Bari"
],
      },
    {
        name: 'Dipon (দিপন)',
        stations:[
  "Tajmahal Road",
  "Salimullah Road",
  "Jakir Hossain Road",
  "Star Kabab",
  "Dhanmondi 15",
  "Jigatola",
  "City College",
  "Science Lab",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "Baitul Mukarram",
  "Gulistan",
  "Motijheel",
  "Arambagh"
],
      },
     
        {
        name: 'Hazi Transport (হাজি ট্রান্সপোর্ট)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Agargaon",
  "Bijoy Sarani",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel"
],
      },
      {
        name: 'Himachal (হিমাচল)',
        stations:[
  "Sony Cinema Hall",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Mohakhali",
  "Gulshan 1",
  "Badda",
  "Rampura Bridge",
  "Rampura Bazar",
  "Khilgaon Khidmah Hospital"
],
      },
    {
        name: 'Himachal Suveccha (হিমাচল শুভেচ্ছা)',
        stations:[
  "Metro Hall",
  "Chasara",
  "Shibu Market",
  "Jalkuri",
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Janapoth Moor",
  "Gulistan",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bangla Motor",
  "Kawran Bazar",
  "Farmgate",
  "Bijoy Sarani",
  "Agargaon",
  "Taltola",
  "Shewrapara",
  "Kazipara",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Pallabi",
  "Mirpur 12"
],
      },
     
        {
        name: 'Himalay (হিমালয়)',
        stations:[
  "Madanpur",
  "Jatrabari",
  "Bangladesh Bank",
  "Mogbazar",
  "Mohakhali",
  "Tongi"
],
      },
       {
        name: 'Itihash (ইতিহাস)',
        stations:[
  "Mirpur 14",
  "Mirpur 10",
  "Mirpur 2",
  "Sony Cinema Hall",
  "Ansar Camp",
  "Technical",
  "Gabtoli",
  "Amin Bazar",
  "Hemayetpur",
  "Savar",
  "Nobinagar",
  "Baipayl",
  "Zirani Bazar",
  "Nandan Park",
  "Chandra"
],
      },
       {
        name: 'J M Super Paribahan (জে এম সুপার পরিবহন)',
        stations:[
  "Jatrabari",
  "Sayadabad",
  "Mugdapara",
  "Bashabo",
  "Khilgaon",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Rampura Bridge",
  "Merul Badda",
  "Uttar Badda",
  "Shahjadpur",
  "Bashtola",
  "Notun Bazar",
  "Nadda",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi"
],
      },
       {
        name: 'Jabale Noor Paribahan (জাবালে নুর পরিবহন)',
        stations:[
  "Agargaon",
  "Taltola",
  "Shewrapara",
  "Kazipara",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Pallabi",
  "Kalshi",
  "Kuril Bishwa Road",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "House Building",
  "Abdullahpur"
],
      },
       {
        name: 'Janjabil (জানযাবিল)',
        stations:[
  "Gabtoli",
  "Mirpur 1",
  "Mirpur 10",
  "Kalshi",
  "Kuril Flyover",
  "Notun Bazar"
],
      },
       {
        name: 'Kamal Plus Paribahan (কামাল প্লাস পরিবহন)',
        stations:[
  "Chittagong Road",
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Sayadabad",
  "Gulistan",
  "Chankhar Pul",
  "Bakshi Bazar",
  "Azimpur",
  "Nilkhet",
  "New Market",
  "Science Lab",
  "City College",
  "Jigatola",
  "Dhanmondi 15",
  "Star Kabab",
  "Shankar",
  "Mohammadpur",
  "Ghatar Char"
],
      },
       {
        name: 'Kanak (কনক)',
        stations:[
  "Mirpur 1",
  "Sony Cinema Hall",
  "Mirpur 2",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur"
],
      },
       {
        name: 'Khajababa (খাজা বাবা)',
        stations:[
  "Jatrabari",
  "Sayadabad",
  "Gulistan",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bangla Motor",
  "Kawran Bazar",
  "Farmgate",
  "Khamar Bari",
  "Agargaon",
  "Taltola",
  "Shewrapara",
  "Kazipara",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Pallabi",
  "Mirpur 12"
],
      },
      {
        name: 'Kironmala Paribahan (কিরণমালা)',
        stations:[
  "Chiriyakhana",
  "Mirpur 1",
  "Sony Cinema Hall",
  "Rupnagar",
  "Birulia",
  "Ashulia",
  "Zirabo",
  "Narsinghapur",
  "Surabari",
  "Jarun",
  "Konabari"
],
      },
       {
        name: 'Labbayek(লাব্বাইক)',
        stations:[
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Mogbazar",
  "Mouchak",
  "Malibaag Moor",
  "Rajarbag",
  "Khilgaon flyover",
  "Bashabo",
  "Mugdapara",
  "Manik Nagar",
  "Golapbagh Chowrasta",
  "Sayadabad",
  "Janapoth Moor",
  "Jatrabari",
  "Kazla",
  "Shonir Akhra",
  "Rayerbag",
  "Matuail",
  "Sign Board"
],
      },
    {
        name: 'Lal Sabuj (লাল সবুজ)',
        stations:[
  "Nandan Park",
  "Zirani Bazar",
  "Baipayl",
  "Nobinagar",
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Motijheel"
],
      },
       {
        name: 'Lams Paribahan (লামস পরিবহন)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 1",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Bijoy Sarani",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "Dainik Bangla Moor",
  "Motijheel"
],
      },
    {
        name: 'Malancha (মালঞ্চ)',
        stations:[
  "Mohammadpur",
  "Shankar",
  "Star Kabab",
  "Dhanmondi 15",
  "Jigatola",
  "City College",
  "Science Lab",
  "Bata Signal",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Dayagonj",
  "Dhupkhola"
],
      },
       {
        name: 'Manjil Express (মাঞ্জিল এক্সপ্রেস)',
        stations:[
  "Chittagong Road",
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Sayadabad",
  "Gulistan",
  "GPO",
  "Paltan",
  "Kakrail",
  "Malibaag Moor",
  "Mouchak",
  "Mogbazar"
],
      },
    {
        name: 'Meghla Transport (মেঘলা ট্রান্সপোর্ট)',
        stations:[
  "Kalabagan",
  "Science Lab",
  "Katabon",
  "Bata Signal",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "Jatrabari",
  "Gulistan",
  "Sayadabad",
  "Jatrabari",
  "Shonir Akhra",
  "Sign Board",
  "Kanchpur",
  "Vulta"
],
      },
       {
        name: 'Meshkat (মেসকাত)',
        stations:[
  "Mohammadpur",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "Paltan",
  "Dainik Bangla Moor",
  "Motijheel",
  "Ittefaq Moor",
  "Sayadabad",
  "Jatrabari",
  "Shonir Akhra",
  "Rayerbag",
  "Matuail",
  "Sign Board",
  "Chittagong Road"
],
      },
    {
        name: 'Midline (মিডলাইন)',
        stations:[
  "Mohammadpur",
  "Shankar",
  "Star Kabab",
  "Dhanmondi 15",
  "Jigatola",
  "City College",
  "Science Lab",
  "Bata Signal",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "Gulistan",
  "Motijheel",
  "Arambagh",
  "Kamalapur",
  "Bashabo",
  "Khilgaon"
],
      },
       {
        name: 'Mirpur Metro Services (মিরপুর মেট্রো সার্ভিস)',
        stations:[
  "Azimpur",
  "Nilkhet",
  "New Market",
  "Science Lab",
  "City College",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Asad Gate",
  "College Gate",
  "Shishu Mela",
  "Shyamoli",
  "Kallyanpur",
  "Darussalam",
  "Technical",
  "Bangla College",
  "Tolarbag",
  "Ansar Camp",
  "Mirpur 1"
],
      },
    {
        name: 'Mirpur Link (মিরপুর লিংক)',
        stations:[
  "ECB Square",
  "Purobi",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Agargaon",
  "Khamar Bari",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "City College",
  "Nilkhet",
  "New Market",
  "Azimpur"
],
      },
       {
        name: 'Mirpur Mission (মিরপুর মিশন)',
        stations: [
    "Chittagong Road",
    "Mirpur 1",
    "Khamar Bari",
    "Farmgate",
    "Press Club",
    "Motijheel"
  ],
      },
       {
        name: 'Mirpur Transport Service (মিরপুর ট্রান্সপোর্ট সার্ভিস)',
        stations:[
    "Gulistan",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Khamar Bari",
    "Agargaon",
    "Taltola",
    "Shewrapara",
    "Kazipara",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Pallabi",
    "Mirpur 12"
  ],
      },
       {
        name: 'Mirpur United Service (মিরপুর ইউনাইটেড সার্ভিস)',
        stations:[
    "Sadarghat",
    "Ray Saheb Bazar",
    "Naya Bazar",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Khamar Bari",
    "Agargaon",
    "Taltola",
    "Shewrapara",
    "Kazipara",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Pallabi",
    "Mirpur 12"
  ],
      },
    {
        name: 'MM Lovely (এম এম লাভলী)',
        stations:[
    "Savar",
    "Hemayetpur",
    "Amin Bazar",
    "Gabtoli",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "College Gate",
    "Asad Gate",
    "Khamar Bari",
    "Farmgate",
    "Kawran Bazar",
    "Bangla Motor",
    "Mogbazar",
    "Mouchak",
    "Malibaag Moor",
    "Mugdapara",
    "Rajarbag",
    "Khilgaon flyover",
    "Bashabo",
    "Mugdapara",
    "Manik Nagar",
    "Golapbagh Chowrasta",
    "Sayadabad",
    "Janapoth Moor",
    "Jatrabari",
    "Kazla",
    "Shonir Akhra",
    "Rayerbag",
    "Matuail",
    "Sign Board"
  ],
      },
       {
        name: 'Modhumita (মধুমিতা)',
        stations:[
    "Chiriyakhana",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "Agargaon",
    "Bijoy Sarani",
    "Jahangir Gate",
    "Mohakhali",
    "Wireless",
    "Abdullahpur",
    "Badda Link Road",
    "Merul Badda",
    "Rampura Bridge",
    "Banasree"
  ],
      },
       {
        name: 'Mohona (মোহনা)',
        stations:[
    "Mirpur 14",
    "Mirpur 10",
    "Mirpur 2",
    "Sony Cinema Hall",
    "Mirpur 1",
    "Mazar Road",
    "Konabari",
    "Rupnagar",
    "Beribadh",
    "Birulia",
    "Ashulia",
    "Zirabo",
    "Fantasy Kingdom"
  ],
      },
     {
        name: 'Moitri (মৈত্রী)',
        stations:[
    "Mohammadpur",
    "Shankar",
    "Star Kabab",
    "Dhanmondi 15",
    "Jigatola",
    "City College",
    "Science Lab",
    "Bata Signal",
    "Shahbag",
    "Matsya Bhaban",
    "High Court",
    "Press Club",
    "Paltan",
    "GPO",
    "Gulistan",
    "Motijheel",
    "Arambagh"
  ],
      },
    
     {
        name: 'Moumita (মৌমিতা)',
        stations:[
    "Chasara",
    "Shibu Market",
    "Jalkuri",
    "Sign Board",
    "Matuail",
    "Rayerbag",
    "Shonir Akhra",
    "Jatrabari",
    "Sayadabad",
    "Gulistan",
    "Chankhar Pul",
    "Bakshi Bazar",
    "Azimpur",
    "Nilkhet",
    "New Market",
    "City College",
    "Kalabagan",
    "Dhanmondi 32",
    "Dhanmondi 27",
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Darussalam",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar",
    "Baipayl",
    "Zirani Bazar",
    "Nandan Park",
    "Chandra"
  ],
      },
    
     {
        name: 'MTCL-2 (এমটিসিএল ২)',
        stations:[
    "Mohammadpur",
    "Asad Gate",
    "Dhanmondi 27",
    "Dhanmondi 32",
    "Shukrabad",
    "Kalabagan",
    "City College",
    "Science Lab",
    "Bata Signal",
    "Shahbag",
    "Matsya Bhaban",
    "High Court",
    "Press Club",
    "Paltan",
    "GPO",
    "Gulistan",
    "Motijheel",
    "Arambagh",
    "Fantasy Kingdom"
  ],
      },
      {
        name: 'Nur E Makka (নূর এ মক্কা)',
        stations:[
    "Chiriyakhana",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Jamuna Future Park",
    "Bashundhara",
    "Nadda",
    "Notun Bazar",
    "Bashtola",
    "Shahjadpur",
    "Uttar Badda",
    "Badda",
    "Madhya Badda",
    "Merul Badda",
    "Rampura Bridge",
    "Rampura Bazar",
    "Hazipara",
    "Malibagh Railgate"
  ],
      },
    {
        name: 'Nabakali (নবকালি)',
        stations:[
    "Chiriyakhana",
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "College Gate",
    "Asad Gate",
    "Dhanmondi 27",
    "Shukrabad",
    "Dhanmondi 32",
    "Kalabagan",
    "Science Lab",
    "Katabon",
    "Shahbag",
    "High Court",
    "Fulbaria",
    "Naya Bazar",
    "Babubazar",
    "Keraniganj"
  ],
      },
     {
        name: 'New Vision (নিউ ভিশন)',
        stations:[
    "Chiriyakhana",
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "College Gate",
    "Asad Gate",
    "Khamar Bari",
    "Farmgate",
    "Kawran Bazar",
    "Bangla Motor",
    "Shahbag",
    "High Court",
    "Press Club",
    "Paltan",
    "Dainik Bangla Moor",
    "Motijheel"
  ],
      },
       {
        name: 'Pallabi Local Service (পল্লবী লোকাল সার্ভিস)',
        stations:[
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Technical",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Chalantika Mor",
    "Mirpur 6",
    "Mirpur 11",
    "Mirpur 12"
  ],
      },
      {
        name: 'Pallabi Super (পল্লবী সুপার)',
        stations:[
    "Gabtoli",
    "Technical",
    "Ansar Camp",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur",
    "Kamarpara"
  ],
      },
      {
        name: 'Paristhan (পরিস্থান)',
        stations:[
    "Bosila",
    "Mohammadpur",
    "Asad Gate",
    "College Gate",
    "Shyamoli",
    "Kallyanpur",
    "Darussalam",
    "Technical",
    "Bangla College",
    "Tolarbag",
    "Ansar Camp",
    "Mirpur 1",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin",
    "Rajlakshmi",
    "House Building",
    "Abdullahpur"
  ],
      },
      {
        name: 'Power Paribahan (পাওয়ার পরিবহন)',
        stations:[
    "Mirpur 14",
    "Mirpur 10",
    "Mirpur 2",
    "Sony Cinema Hall",
    "Mirpur 1",
    "Mazar Road",
    "Konabari",
    "Rupnagar",
    "Beribadh",
    "Birulia",
    "Ashulia",
    "Zirabo",
    "Narsinghapur",
    "Surabari",
    "Jarun",
    "Konabari"
  ],
      },
    {
        name: 'Prattay (প্রত্যয়)',
        stations:[
    "Gabtoli",
    "Beribadh Tin Rastar Moor",
    "Rayer Bazar",
    "Sikder Medical College",
    "Hazaribag",
    "Kamrangirchar",
    "Showari Ghat",
    "Babubazar"
  ], 
      },
      {
        name: 'Prochesta (প্রচেষ্টা)',
        stations:[
    "Maowa",
    "Keraniganj",
    "Babubazar",
    "Naya Bazar",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Badda",
    "Uttar Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur"
  ], 
      },
    {
        name: 'Projapati (প্রজাপতি)',
        stations:[
    "Bosila",
    "Mohammadpur",
    "Asad Gate",
    "College Gate",
    "Shyamoli",
    "Kallyanpur",
    "Darussalam",
    "Technical",
    "Bangla College",
    "Ansar Camp",
    "Mirpur 1",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin",
    "Rajlakshmi",
    "House Building",
    "Abdullahpur",
    "Kamarpara"
  ], 
      },
      {
        name: 'Provati Banasree (প্রভাতী বনশ্রী)',
        stations:[
    "Fulbaria",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mogbazar",
    "Sat rasta",
    "Nabisco",
    "Mohakhali",
    "Chairman Bari",
    "Banani",
    "Kakali",
    "Staff Road",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur",
    "Tongi",
    "Station Road",
    "Mill Gate",
    "Board Bazar",
    "Gazipur Chourasta",
    "Joydebpur",
    "Sreepur",
    "Barmi"
  ], 
      },
    {
        name: 'Purbachol Logistics (পূর্বাচল লজিস্টিকস)',
        stations:[
    "Mirpur 14",
    "Mirpur 10",
    "Mirpur 2",
    "Sony Cinema Hall",
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar",
    "Baipayl",
    "Zirani Bazar",
    "Nandan Park",
    "Chandra"
  ], 
      },
      {
        name: 'Raida (রাইদা)',
        stations:[
    "Postogola",
    "Dholairpar",
    "Jatrabari",
    "Janapoth Moor",
    "Sayapabad",
    "Mugdapara",
    "Bashabo",
    "Khilgaon",
    "Malibagh Railgate",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Badda",
    "Uttar Badda",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Chourasta",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Dia Bari"
  ], 
      },
    {
        name: 'Raja City (রাজা সিটি)',
        stations:[
    "Postogola",
    "Jurain",
    "Dayagonj",
    "Gulistan",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Shahbag",
    "Bata Signal",
    "Science Lab",
    "City College",
    "Jigatola",
    "Dhanmondi 15",
    "Star Kabab",
    "Shankar",
    "Mohammadpur",
    "Bosila",
    "Ghatar Char"
  ], 
      },
      {
        name: 'Rajanigandha (রজনীগন্ধা)',
        stations:[
    "Chittagong Road",
    "Sign Board",
    "Matuail",
    "Rayerbag",
    "Shonir Akhra",
    "Jatrabari",
    "Sayapabad",
    "Gulistan",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Shahbag",
    "Bata Signal",
    "Science Lab",
    "Jigatola",
    "Dhanmondi",
    "Star Kabab",
    "Shankar",
    "Mohammadpur"
  ], 
      },
    {
        name: 'Rajdhani Super (রাজধানী)',
        stations:[
    "Hemayetpur",
    "Gabtoli",
    "Technical",
    "Ansar Camp",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Jamuna Future Park",
    "Bashundhara",
    "Nadda",
    "Notun Bazar",
    "Bashtola",
    "Shahjadpur",
    "Uttar Badda",
    "Badda",
    "Madhya Badda",
    "Merul Badda",
    "Rampura Bridge",
    "Banasree",
    "Demra Staff Quarter"
  ], 
      },
      {
        name: 'Ramjan (রমজান)',
        stations:[
    "Gabtoli",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "College Gate",
    "Asad Gate",
    "Mohammadpur",
    "Shankar",
    "Star Kabab",
    "Dhanmondi 15",
    "Jigatola",
    "City College",
    "Science Lab",
    "Bata Signal",
    "Shahbag",
    "Matsya Bhaban",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Banasree",
    "Demra Staff Quarter"
  ], 
      },
    {
        name: 'Robrob (রবরব)',
        stations:[
    "Gabtoli",
    "Technical",
    "Ansar Camp",
    "Mirpur 1",
    "Mirpur 2",
    "Mirpur 10",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Banani",
    "Kakali",
    "Abdullahpur",
    "Badda Link Road",
    "Merul Badda",
    "Rampura Bridge",
    "Banasree"
  ],
      },
      {
        name: 'Rois (রাইস)',
        stations:[
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Kazipara",
    "Shewrapara",
    "Agargaon",
    "Mohakhali",
    "Abdullahpur",
    "Badda",
    "Rampura Bridge",
    "Banasree"
  ], 
      },
    {
        name: 'Rongdhonu Express (রংধনু এক্সপ্রেস)',
        stations:[
    "Adabor",
    "Mohammadpur",
    "Shia Masjid",
    "Shyamoli",
    "College Gate",
    "Asad Gate",
    "Kalabagan",
    "Science Lab",
    "Katabon",
    "Bata Signal",
    "Shahbag",
    "Kakrail",
    "Fakirapul",
    "Motijheel",
    "Dayagonj",
    "Postogola"
  ], 
      },
      {
        name: 'Runway Express (রানওয়ে এক্সপ্রেস)',
        stations:[
    "Keraniganj",
    "Kadamtali",
    "Babubazar",
    "Naya Bazar",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Press Club",
    "High Court",
    "Matsya Bhaban",
    "Shahbag",
    "Bangla Motor",
    "Kawran Bazar",
    "Farmgate",
    "Agargaon",
    "Shewrapara",
    "Kazipara",
    "Mirpur 10",
    "Mirpur 11",
    "Mirpur 12",
    "ECB Square"
  ], 
      },
    {
        name: 'Rupa Paribahan (রুপা পরিবহন)',
        stations:[
    "Gabtoli",
    "Technical",
    "Ansar Camp",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 14"
  ],
      },
      {
        name: 'Rupkotha (রুপকথা)',
        stations:[
    "Gabtoli",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Mirpur 11",
    "Purobi",
    "Kalshi",
    "ECB Square",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur"
  ], 
      },
    {
        name: 'Safety Druti (সেফটি দ্রুতি)',
        stations:[
    "Mirpur 12",
    "Pallabi",
    "Purobi",
    "Mirpur 11",
    "Mirpur 10",
    "Kazipara",
    "Shewrapara",
    "Taltola",
    "Agargaon",
    "Khamar Bari",
    "Dhanmondi 27",
    "Dhanmondi 32",
    "Kalabagan",
    "City College",
    "New Market",
    "Nilkhet",
    "Azimpur"
  ],
      },
      {
        name: 'Sakalpa Transport (স্বকল্প ট্রান্সপোর্ট)',
        stations:[
    "Chiriyakhana",
    "Mirpur 1",
    "Sony Cinema Hall",
    "Mirpur 2",
    "Mirpur 10",
    "Kazipara",
    "Shewrapara",
    "Agargaon",
    "Bijoy Sarani",
    "Farmgate",
    "Bangla Motor",
    "Mogbazar",
    "Malibaag Moor",
    "Kamalapur"
  ],
 
      },
    {
        name: 'Salsabil (ছালছাবিল)',
        stations:[
  "Postogola",
  "Dholairpar",
  "Jatrabari",
  "Sayapabad",
  "Mugdapara",
  "Bashabo",
  "Khilgaon",
  "Malibagh Railgate",
  "Rampura Bazar",
  "Rampura Bridge",
  "Merul Badda",
  "Badda",
  "Uttar Badda",
  "Bashtola",
  "Notun Bazar",
  "Nadda",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Chourasta",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Bypass",
  "Gazipur Chourasta"
], 
      },
      {
        name: 'Savar Paribahan (সাভার পরিবহন)',
        stations:[
  "Sadarghat",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Science Lab",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Asad Gate",
  "College Gate",
  "Shishu Mela",
  "Shyamoli",
  "Kallyanpur",
  "Darussalam",
  "Technical",
  "Gabtoli",
  "Amin Bazar",
  "Hemayetpur",
  "Savar",
  "Baipayl",
  "Zirani Bazar",
  "Nandan Park"
],
      },
    {
        name: 'Shadhin (স্বাধীন)',
        stations:[
  "Bosila",
  "Mohammadpur",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Mogbazar",
  "Mouchak",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Rampura Bridge",
  "Banasree",
  "Demra Staff Quarter"
], 
      },
      {
        name: 'Shadhin Express (স্বাধীন এক্সপ্রেস)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Golap Shah Mazar",
  "Naya Bazar",
  "Babubazar",
  "Keraniganj",
  "Kadamtali",
  "Rajendrapur",
  "Maowa"
],
      },
    {
        name: 'Shahria Enterprise (শাহরিয়া এন্টারপ্রাইজ)',
        stations:[
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Dhanmondi 27",
  "Dhanmondi 32",
  "Shukrabad",
  "Kalabagan",
  "City College",
  "Science Lab",
  "Katabon",
  "Shahbag",
  "Matsya Bhaban",
  "Kakrail",
  "Arambagh",
  "Motijheel",
  "Ittefaq Moor",
  "Tikatuli",
  "Dayagonj",
  "Gandaria",
  "Jurain",
  "Postogola"
],
      },
      {
        name: 'Shatabdi (শতাব্দি)',
        stations:[
  "Motijheel",
  "Paltan",
  "Kakrail",
  "Malibaag Moor",
  "Mouchak",
  "Mogbazar",
  "Sat rasta",
  "Nabisco",
  "Mohakhali",
  "Chairman Bari",
  "Banani",
  "Kakali",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Kamarpara"
], 
      },
    {
        name: 'Shikhor Paribahan (শিখর পরিবহন)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Bijoy Sarani",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Gulistan",
  "Janapoth Moor",
  "Jatrabari"
], 
      },
      {
        name: 'Shikhor Paribahan (শিখর পরিবহন)',
        stations:[
  "Jatrabari",
  "Sayapabad",
  "Gulistan",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bangla Motor",
  "Kawran Bazar",
  "Farmgate",
  "Bijoy Sarani",
  "Agargaon",
  "IDB",
  "Taltola",
  "Shewrapara",
  "Kazipara",
  "Mirpur 10",
  "Mirpur 11",
  "Pallabi",
  "Purobi",
  "Mirpur 12"
],
      },
    {
        name: 'Suveccha (শুভেচ্ছা)',
        stations:[
  "Chittagong Road",
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Sayapabad",
  "Gulistan",
  "Chankhar Pul",
  "Bakshi Bazar",
  "Dhakeshwari",
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Asad Gate",
  "College Gate",
  "Shishu Mela",
  "Shyamoli",
  "Kallyanpur",
  "Darussalam",
  "Technical",
  "Gabtoli",
  "Amin Bazar",
  "Hemayetpur",
  "Savar",
  "Nobinagar",
  "Baipayl",
  "Zirani Bazar",
  "Nandan Park",
  "Chandra"
], 
      },
      {
        name: 'Suvojatri (শুভযাত্রী)',
        stations:[
  "Fulbaria",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bata Signal",
  "Science Lab",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Asad Gate",
  "College Gate",
  "Shishu Mela",
  "Shyamoli",
  "Kallyanpur",
  "Darussalam",
  "Technical",
  "Gabtoli",
  "Amin Bazar",
  "Hemayetpur",
  "Manikganj"
], 
      },
    {
        name: 'Siam Transport (সিয়াম ট্রান্সপোর্ট)',
        stations:[
  "Banasree",
  "Rampura Bridge",
  "Merul Badda",
  "Badda",
  "Shahjadpur",
  "Bashtola",
  "Notun Bazar",
  "Nadda",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Kamarpara",
  "Dhour",
  "Beribadh",
  "Ashulia",
  "Zirabo",
  "Fantasy Kingdom",
  "Jamgora",
  "Shimultola",
  "Baipayl",
  "Palli Bidyut",
  "Savar Cantonment",
  "Nobinagar"
], 
      },
      {
        name: 'Skyline (স্কাই লাইন)',
        stations:[
  "Sadarghat",
  "Ray Saheb Bazar",
  "Naya Bazar",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibaag Moor",
  "Mouchak",
  "Nabisco",
  "Mohakhali",
  "Chairman Bari",
  "Sainik Club",
  "Banani",
  "Kakali",
  "Staff Road",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi",
  "Station Road",
  "Mill Gate",
  "Board Bazar",
  "Gazipur Chourasta"
],
      },
    {
        name: 'Somota Paribahan (সমতা পরিবহন)',
        stations:[
  "Chittagong Road",
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Sayapabad",
  "Gulistan",
  "Chankhar Pul",
  "Bakshi Bazar",
  "Dhakeshwari",
  "Azimpur",
  "Nilkhet",
  "New Market",
  "City College",
  "Kalabagan",
  "Dhanmondi 32",
  "Dhanmondi 27",
  "Asad Gate",
  "College Gate",
  "Shishu Mela",
  "Shyamoli",
  "Kallyanpur",
  "Darussalam",
  "Technical",
  "Ansar Camp",
  "Mirpur 1",
  "Abdullahpur"
], 
      },
      {
        name: 'Somoy (সময়)',
        stations:[
  "Sign Board",
  "Matuail",
  "Rayerbag",
  "Shonir Akhra",
  "Jatrabari",
  "Sayapabad",
  "Janapoth Moor",
  "Gulistan",
  "GPO",
  "Paltan",
  "Press Club",
  "High Court",
  "Matsya Bhaban",
  "Shahbag",
  "Bangla Motor",
  "Kawran Bazar",
  "Farmgate",
  "Bijoy Sarani",
  "Agargaon",
  "IDB",
  "Taltola",
  "Shewrapara",
  "Kazipara",
  "Mirpur 10",
  "Mirpur 11",
  "Pallabi",
  "Purobi",
  "Mirpur 12"
], 
      },
    {
        name: 'Somoy Niyantran (সময় নিয়ন্ত্রণ)',
        stations:[
  "Mirpur 12",
  "Pallabi",
  "Purobi",
  "Mirpur 11",
  "Mirpur 10",
  "Kazipara",
  "Shewrapara",
  "Taltola",
  "Agargaon",
  "Bijoy Sarani",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "Matsya Bhaban",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Golap Shah Mazar",
  "Naya Bazar",
  "Babubazar",
  "Keraniganj"
], 
      },
      {
        name: 'Super (সুপার)',
        stations:[
  "Gulistan",
  "Shahbag",
  "Farmgate",
  "Shyamoli",
  "Gabtoli",
  "Savar",
  "Nobinagar"
], 
      },
       {
        name: 'Supravat (সুপ্রভাত)',
        stations:[
  "Victoria Park",
  "Sadarghat",
  "Ray Saheb Bazar",
  "Golap Shah Mazar",
  "GPO",
  "Paltan",
  "Kakrail",
  "Shantinagar",
  "Malibaag Moor",
  "Mouchak",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Rampura Bridge",
  "Merul Badda",
  "Badda",
  "Shahjadpur",
  "Bashtola",
  "Notun Bazar",
  "Nadda",
  "Bashundhara",
  "Jamuna Future Park",
  "Kuril Bishwa Road",
  "Khilkhet",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "Azampur",
  "House Building",
  "Abdullahpur",
  "Tongi"
], 
      },
    {
        name: 'Swajan Paribahan (স্বজন পরিবহন)',
        stations:[
  "Savar",
  "Hemayetpur",
  "Amin Bazar",
  "Gabtoli",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Golap Shah Mazar",
  "Naya Bazar",
  "Ray Saheb Bazar",
  "Sadarghat"
],
      },
      {
        name: 'Talukdar (তালুকদার)',
        stations:[
  "Chiriyakhana",
  "Mirpur 1",
  "Ansar Camp",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Mogbazar",
  "Mouchak",
  "Malibaag Moor",
  "Mugdapara",
  "Rajarbag",
  "Khilgaon flyover",
  "Bashabo",
  "Mugdapara",
  "Manik Nagar",
  "Golapbagh Chowrasta",
  "Sayapabad",
  "Janapoth Moor",
  "Jatrabari",
  "Kazla",
  "Shonir Akhra",
  "Rayerbag",
  "Matuail",
  "Sign Board",
  "Sanarpar",
  "Chittagong Road"
], 
      },
     {
        name: 'Tanjil Paribahan (তানজিল পরিবহন)',
        stations:[
  "Chiriyakhana",
  "Mirpur 1",
  "Ansar Camp",
  "Technical",
  "Kallyanpur",
  "Shyamoli",
  "Shishu Mela",
  "College Gate",
  "Asad Gate",
  "Khamar Bari",
  "Farmgate",
  "Kawran Bazar",
  "Bangla Motor",
  "Shahbag",
  "High Court",
  "Press Club",
  "Paltan",
  "GPO",
  "Golap Shah Mazar",
  "Naya Bazar",
  "Ray Saheb Bazar",
  "Sadarghat"
], 
      },
    {
        name: 'Taranga Plus (তরঙ্গ প্লাস)',
        stations:[
  "Mohammadpur",
  "Shankar",
  "Star Kabab",
  "Dhanmondi 15",
  "Jigatola",
  "City College",
  "Science Lab",
  "Bata Signal",
  "Shahbag",
  "Matsya Bhaban",
  "Kakrail",
  "Shantinagar",
  "Malibaag Moor",
  "Mouchak",
  "Malibagh Railgate",
  "Hazipara",
  "Rampura Bazar",
  "Rampura Bridge",
  "Banasree",
  "South Banasree"
], 
      },
      {
        name: 'Tetulia (তেতুলিয়া)',
        stations:[
  "Shia Masjid",
  "Japan Garden City",
  "Ring Road",
  "Adabor",
  "Shyamoli",
  "Shishu Mela",
  "Agargaon",
  "Taltola",
  "Shewrapara",
  "Kazipara",
  "Mirpur 10",
  "Mirpur 11",
  "Purobi",
  "Pallabi",
  "Kalshi",
  "ECB Square",
  "MES",
  "Shewra",
  "Kuril Bishwa Road",
  "Airport",
  "Jashimuddin (Uttara)",
  "Rajlakshmi",
  "House Building",
  "Abdullahpur"
], 
      },
     {
        name: 'Thikana (ঠিকানা)',
        stations:[
    "Sign Board",
    "Matuail",
    "Rayerbag",
    "Shonir Akhra",
    "Jatrabari",
    "Sayapabad",
    "Gulistan",
    "Chankhar Pul",
    "Bakshi Bazar",
    "Dhakeshwari",
    "Azimpur",
    "Nilkhet",
    "New Market",
    "City College",
    "Kalabagan",
    "Dhanmondi 32",
    "Dhanmondi 27",
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Darussalam",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar",
    "Baipayl",
    "Zirani Bazar",
    "Nandan Park",
    "Chandra"
  ], 
      },
    {
        name: 'Thikana Express (ঠিকানা এক্সপ্রেস)',
        stations:[
    "Shonbari Sreenagar",
    "Nimtola",
    "Kuchimura",
    "Rajendrapur",
    "Hasnabad",
    "Postogola",
    "Jurain",
    "Dholairpar",
    "Jatrabari",
    "Sayapabad",
    "Gulistan",
    "Chankhar Pul",
    "Bakshi Bazar",
    "Azimpur",
    "Nilkhet",
    "New Market",
    "City College",
    "Kalabagan",
    "Dhanmondi 32",
    "Dhanmondi 27",
    "Asad Gate",
    "College Gate",
    "Shishu Mela",
    "Shyamoli",
    "Kallyanpur",
    "Darussalam",
    "Technical",
    "Gabtoli",
    "Amin Bazar",
    "Hemayetpur",
    "Savar",
    "Baipayl",
    "Zirani Bazar",
    "Nandan Park",
    "Chandra"
  ], 
      },
      {
        name: 'Titas (তিতাস)',
        stations:[
    "Chiriyakhana",
    "Mirpur 1",
    "Gabtoli",
    "Savar",
    "Nobinagar",
    "Chandra"
  ], 
      },
     {
        name: 'Transilva (ট্রান্সিল্ভা)',
        stations:[
    "Mirpur 1",
    "Ansar Camp",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "College Gate",
    "Asad Gate",
    "Dhanmondi 27",
    "Dhanmondi 32",
    "Kalabagan",
    "Science Lab",
    "Bata Signal",
    "Shahbag",
    "Matsya Bhaban",
    "High Court",
    "Press Club",
    "Paltan",
    "GPO",
    "Gulistan",
    "Motijheel",
    "Sayapabad",
    "Janapoth Moor",
    "Jatrabari"
  ], 
      },
    {
        name: 'Trust Transport Services (ট্রাষ্ট ট্রান্সপোর্ট)',
        stations:[
    "Mirpur 10",
    "Mirpur 13",
    "Mirpur 14",
    "Kochukhet",
    "Sainik Club",
    "Banani"
  ], 
      },
      {
        name: 'Trust Transport Services (ট্রাষ্ট ট্রান্সপোর্ট)',
        stations:[
    "Mirpur 10",
    "Mirpur 13",
    "Mirpur 14",
    "Kochukhet",
    "Workshop",
    "Saudi Colony",
    "Jahangir Gate",
    "Farmgate",
    "Kawran Bazar",
    "Bangla Motor",
    "Shahbag"
  ], 
      },
     {
        name: 'Trust Transport Services (ট্রাষ্ট ট্রান্সপোর্ট)',
        stations:[
    "Mirpur (DOHS)",
    "Kalshi",
    "ECB Square",
    "Garrison (Cantonment)",
    "Adamjee School",
    "Workshop",
    "Saudi Colony",
    "Jahangir Gate",
    "Farmgate",
    "Kawran Bazar",
    "Bangla Motor",
    "Shahbag",
    "High Court",
    "Press Club",
    "Paltan",
    "Dainik Bangla Moor",
    "Motijheel"
  ], 
      },
    {
        name: 'Trust Transport Services (AC) (ট্রাষ্ট ট্রান্সপোর্ট)',
        stations:[
    "Mirpur (DOHS)",
    "Kalshi",
    "ECB Square",
    "Garrison (Cantonment)",
    "Adamjee School",
    "Workshop",
    "Saudi Colony",
    "Jahangir Gate",
    "Farmgate",
    "Kawran Bazar"
  ], 
      },
      {
        name: 'Turag (তুরাগ)',
        stations:[
    "Jatrabari",
    "Sayapabad",
    "Mugdapara",
    "Bashabo",
    "Khilgaon",
    "Malibaag Moor",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Badda",
    "Uttar Badda",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur",
    "Tongi"
  ], 
      },
       {
        name: 'Victor Classic (ভিক্টর ক্লাসিক)',
        stations:[
    "Sadarghat",
    "Ray Saheb Bazar",
    "Naya Bazar",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road"
  ],
      },
       {
        name: 'Victor Paribahan (ভিক্টর পরিবহন)',
        stations:[
    "Sadarghat",
    "Ray Saheb Bazar",
    "Naya Bazar",
    "Golap Shah Mazar",
    "GPO",
    "Paltan",
    "Kakrail",
    "Shantinagar",
    "Malibaag Moor",
    "Mouchak",
    "Malibagh Railgate",
    "Hazipara",
    "Rampura Bazar",
    "Rampura Bridge",
    "Merul Badda",
    "Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road"
  ], 
      },
       {
        name: 'V.I.P (ভি,আই,পি)',
        stations:[
    "Azimpur",
    "Nilkhet",
    "New Market",
    "City College",
    "Kalabagan",
    "Banani",
    "Kakali",
    "MES",
    "Shewra",
    "Kuril Bishwa Road",
    "Khilkhet",
    "Airport",
    "Jashimuddin (Uttara)",
    "Rajlakshmi",
    "Azampur",
    "House Building",
    "Abdullahpur",
    "Tongi",
    "Station Road",
    "Mill Gate",
    "Board Bazar",
    "Gazipur Chourasta"
  ], 
      },
       {
        name: 'Welcome (ওয়েলকাম)',
        stations:[
    "Nandan Park",
    "Zirani Bazar",
    "Baipayl",
    "Nobinagar",
    "Savar",
    "Hemayetpur",
    "Amin Bazar",
    "Gabtoli",
    "Technical",
    "Kallyanpur",
    "Shyamoli",
    "Shishu Mela",
    "College Gate",
    "Asad Gate",
    "Khamar Bari",
    "Farmgate",
    "Kawran Bazar",
    "Bangla Motor",
    "Shahbag",
    "High Court",
    "Press Club",
    "Paltan",
    "GPO",
    "Gulistan",
    "Motijheel"
  ], 
      },
       {
        name: 'Winner (উইনার)',
        stations:[
    "Azimpur",
    "Eden College",
    "Nilkhet",
    "New Market",
    "Science Lab",
    "City College",
    "Kalabagan",
    "Panthopoth",
    "Kawran Bazar",
    "Bot tola",
    "Nabisco",
    "Mohakhali",
    "Wireless",
    "Gulshan 1",
    "Badda",
    "Badda Link Road",
    "Uttar Badda",
    "Shahjadpur",
    "Bashtola",
    "Notun Bazar",
    "Nadda",
    "Bashundhara",
    "Jamuna Future Park",
    "Kuril Bishwa Road"
  ], 
      },
       {
        name: 'Deepan (দিপান)',
        stations:[
    "Tajmahal Road",
    "Shankar",
    "Dhanmondi 15",
    "Jigatola",
    "City College",
    "Science Lab",
    "Shahbag",
    "Matsya Bhaban",
    "Paltan",
    "Gulistan",
    "Motijheel",
    "Arambagh"
  ], 
      },
    
    
    ];

 // Search logic
    function searchRoutes() {
      const from = document.getElementById('from').value.trim();
      const to = document.getElementById('to').value.trim();
      const resultDiv = document.getElementById('results');
      resultDiv.innerHTML = '';

      if (!from || !to) {
        resultDiv.innerHTML = '<p style="color:red;">Please enter both From and To stations.</p>';
        return;
      }

      const matchingOperators = operators.filter(op =>
        op.stations.includes(from) && op.stations.includes(to)
      );

      if (matchingOperators.length > 0) {
        resultDiv.innerHTML = '<h3>Operators serving this route:</h3>';

        const container = document.createElement('div'); // container div

        matchingOperators.forEach(op => {
          const item = document.createElement('div'); // individual operator box
          item.textContent = op.name;
          item.className = 'result-item'; // apply style
          container.appendChild(item);
        });

        resultDiv.appendChild(container);
      } else {
        resultDiv.innerHTML = `<p>No operators found for route from <strong>${from}</strong> to <strong>${to}</strong>.</p>`;
      }
    }







